config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :provider_organizations
  resources :credentials
  resources :requirements
  resources :profiles
  
  resources :imports


  devise_for :users,
    controllers: {
      sessions:           'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

    resources :users, except: :new
    resources :patients
    resources :documented_units
    resources :codes

    resources :visits do
      collection do
        post :import
      end
    end

  get 'welcome/index'
  # Defines the root path route ("/")
  root 'welcome#index'
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :patient

  has_many :documented_units
  has_many :applied_codes, -> { distinct }, through: :documented_units, source: :code

  # validates_uniqueness_of :webptvisitid
  validates_uniqueness_of :patient, :scope => [:date_of_service, :webptvisitid] # add discipline, or get discipline from looking up the discipline of the documenting therapist
  validates :date_of_service, presence: true
  # validates :webptvisitid, , numericality: true

  validates :webptvisitid, presence: true, if: Proc.new { |v| v.webptvisitid.present? }
  validates :webptvisitid, uniqueness: true, if: Proc.new { |v| v.webptvisitid.present? }
  validates :webptvisitid, numericality: true, if: Proc.new { |v| v.webptvisitid.present? }

  



end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  require 'csv'

  before_action :set_visit, only: %i[ show edit update destroy ]

  # GET /visits or /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1 or /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits or /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully created." }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1 or /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully updated." }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1 or /visits/1.json
  def destroy
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url, notice: "Visit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visit_params
      params.require(:visit).permit(:date_of_service, :patient_id, :provider_organization_id)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_with(model: visit) do |form| %>
  <% if visit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
        <% visit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date_of_service, style: "display: block" %>
    <%= form.date_field :date_of_service %>
  </div>

  <div>
    <%= form.label :provider_organization_id, style: "display: block" %>
    <%= form.select(:provider_organization_id, ProviderOrganization.all.collect { |po| [ po.name, po.id ] }, { include_blank: true }, { "data-placeholder": 'Select Provider Organization' }) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/visits/_visit.html.erb
<div id="<%= dom_id visit %>">
  <p>
    <strong>Date of service:</strong>
    <%= visit.date_of_service %>
  </p>

  <p>
    <strong>Patient:</strong>
    <%= visit.patient_id %>
  </p>

</div>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render "form", visit: @visit %>

<br>

<div>
  <%= link_to "Show this visit", @visit %> |
  <%= link_to "Back to visits", visits_path %>
</div>

app/views/visits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Visits</h1>

<%= link_to "New visit", new_visit_path %><br>

========  

<%# This may be useful later? %>
<% if false %>
  <%= form_with url: import_visits_path, method: :post do |form| %>
    <%= form.file_field :file, accept: ".csv" %>
    <%= form.button "Import" %>
  <% end %>
<% end %>


<div id="visits">
  <% @visits.each do |visit| %>
    <p>
      <%= link_to "#{visit.patient.name} on #{visit.date_of_service.strftime("%m/%d/%Y")}", visit %>
    </p>
  <% end %>
</div>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render "form", visit: @visit %>

<br>

<div>
  <%= link_to "Back to visits", visits_path %>
</div>

app/views/visits/show.html.erb
<p style="color: green"><%= notice %></p>

<p>Patient ID: <%= @visit.patient_id %> </p>
<p>Patient: <%= patient_full_name(@visit.patient) %> </p>
<p> DOS: <%= @visit.date_of_service %> </p>
<table>
  <% @visit.applied_codes.pluck(:label, :unit_count).each do |ap| %>
    <% if ap.last == 1 %>
      <tr><%= ap.first %> ( <%= ap.last %>  unit )</tr>
      <% else %>
      <tr><%= ap.first %> ( <%= ap.last %>  units )</tr>
    <% end %>
    <br>
  <% end %>
</table>


<div>
  <%= link_to "Edit this visit", edit_visit_path(@visit) %> |
  <%= link_to "Back to visits", visits_path %>

  <%= button_to "Destroy this visit", @visit, method: :delete %>
</div>