config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :provider_organizations
  resources :credentials
  resources :requirements
  resources :profiles
  
  resources :imports


  devise_for :users,
    controllers: {
      sessions:           'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

    resources :users, except: :new
    resources :patients
    resources :documented_units
    resources :codes

    resources :visits do
      collection do
        post :import
      end
    end

  get 'welcome/index'
  # Defines the root path route ("/")
  root 'welcome#index'
end

app/models/provider_organization.rb
class ProviderOrganization < ApplicationRecord
    enum kind: [:home_health_agency, :surgery_center] # Alias "Type" cannot be used since it is a reserved keyword for database field names

    has_many :patient_entities, dependent: :destroy, inverse_of: :provider_organization
    has_many :censused_patients, -> { distinct }, through: :patient_entities, :source => :patient

    has_many :provider_entities, dependent: :destroy, inverse_of: :provider_organization
    has_many :rostered_providers, -> { distinct }, through: :provider_entities, :source => :profile

    has_one :address, as: :addressable, dependent: :destroy
    accepts_nested_attributes_for :address
end

app/controllers/provider_organizations_controller.rb
class ProviderOrganizationsController < ApplicationController
  before_action :set_provider_organization, only: %i[ show edit update destroy ]

  # GET /provider_organizations or /provider_organizations.json
  def index
    @provider_organizations = ProviderOrganization.all
  end

  # GET /provider_organizations/1 or /provider_organizations/1.json
  def show
  end

  # GET /provider_organizations/new
  def new
    @provider_organization = ProviderOrganization.new
  end

  # GET /provider_organizations/1/edit
  def edit
  end

  # POST /provider_organizations or /provider_organizations.json
  def create
    @provider_organization = ProviderOrganization.new(provider_organization_params)

    respond_to do |format|
      if @provider_organization.save
        format.html { redirect_to provider_organization_url(@provider_organization), notice: "Provider organization was successfully created." }
        format.json { render :show, status: :created, location: @provider_organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @provider_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provider_organizations/1 or /provider_organizations/1.json
  def update
    respond_to do |format|
      if @provider_organization.update(provider_organization_params)
        format.html { redirect_to provider_organization_url(@provider_organization), notice: "Provider organization was successfully updated." }
        format.json { render :show, status: :ok, location: @provider_organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @provider_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provider_organizations/1 or /provider_organizations/1.json
  def destroy
    @provider_organization.destroy

    respond_to do |format|
      format.html { redirect_to provider_organizations_url, notice: "Provider organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider_organization
      @provider_organization = ProviderOrganization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def provider_organization_params
      params.require(:provider_organization).permit(:name, :kind, address_attributes: [:id, :streetLineOne, :streetLineTwo, :city, :state, :zip_code], censused_patient_ids: [], rostered_provider_ids: [])
    end
end

app/helpers/provider_organizations_helper.rb
module ProviderOrganizationsHelper
end

app/views/provider_organizations/_form.html.erb
<%= form_with(model: provider_organization, class: "contents") do |form| %>
  <% if provider_organization.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(provider_organization.errors.count, "error") %> prohibited this provider_organization from being saved:</h2>

      <ul>
        <% provider_organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="p-2 space-y-1">
    <%= form.label :name, class: "block" %>
    <%= form.text_field :name, class: "min-w-full sm:min-w-72 max-w-xl" %>
  </div>

  <div class="p-2 space-y-1">
    <%= form.label :kind, "Type", class: "block" %>
    <%= form.select(:kind, ProviderOrganization.kinds.map { |key, value| [key.humanize, key] }, { include_blank: true }, { class: "min-w-full sm:min-w-72 max-w-xl" }) %>
  </div>

    <%= form.fields_for :address, Address.new do |ff| %>
      <div class="p-2 space-y-1">
        <%= ff.label :address_line_1, class: "block" %>
        <%= ff.text_field :streetLineOne, class: "min-w-full sm:min-w-72 max-w-xl" %>
      </div>

      <div class="p-2 space-y-1">
        <%= ff.label :address_line_2, class: "block" %>
        <%= ff.text_field :streetLineTwo, class: "min-w-full sm:min-w-72 max-w-xl" %>
      </div>

      <div class="p-2 space-y-1">
        <%= ff.label :city, class: "block" %>
        <%= ff.text_field :city, class: "min-w-full sm:min-w-72 max-w-xl" %>
      </div>

      <div class="p-2 space-y-1">
        <%= ff.label :state, class: "block" %>
        <%= ff.text_field :state, class: "min-w-full sm:min-w-72 max-w-xl" %>
      </div>

      <div class="p-2 space-y-1">
        <%= ff.label :zip_code, class: "block" %>
        <%= ff.text_field :zip_code, class: "min-w-full sm:min-w-72 max-w-xl" %>
      </div>
    <% end %>    

  <div class="actions p-2 space-y-1">
    <%= form.submit class: "bg-blue-500 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/provider_organizations/_provider_organization.html.erb
<div id="<%= dom_id provider_organization %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= provider_organization.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= provider_organization.kind.humanize %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show", provider_organization, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit", edit_provider_organization_path(provider_organization), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/provider_organizations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing provider organization</h1>

  <%= render "form", provider_organization: @provider_organization %>

  <%= link_to "Show this provider organization", @provider_organization, class: "ml-2 rounded-lg py-3 px-5 bg-gray-600 inline-block font-medium" %>
  <%= link_to "Back to provider organizations", provider_organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/provider_organizations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Provider organizations</h1>
    <%= link_to "New provider organization", new_provider_organization_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
</div>

<div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Name
                </th>
                <th scope="col" class="hidden px-6 py-3 sm:table-cell">
                    Type
                </th>
                <th scope="col" class="px-6 py-3">
                    Show
                </th>
                <th scope="col" class="px-6 py-3">
                    Edit
                </th>
            </tr>
        </thead>
        <tbody>
            <% @provider_organizations.each do |pe| %>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    <%= pe.name %>
                    <dl class="sm:hidden">
                      <dd><%= pe.kind.humanize %></dd>
                    </dl>
                  </td>
                  <td class="hidden px-6 py-4 sm:table-cell">
                      <%= pe.kind.humanize %>
                  </td>
                  <td class="px-6 py-4">
                      <%= link_to "Show", pe %>
                  </td>
                  <td class="px-6 py-4">
                    <%= link_to "Edit", edit_provider_organization_path(pe) %>
                  </td>
              </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/provider_organizations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New provider organization</h1>

  <%= render "form", provider_organization: @provider_organization %>

  <%= link_to "Back to provider organizations", provider_organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/provider_organizations/show.html.erb
<div class="mx-auto w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @provider_organization %>

    <div class="flex flex-wrap space-x-2">
      <%= link_to "Edit", edit_provider_organization_path(@provider_organization), class: "text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-3" %>
      <%= button_to "Delete", provider_organization_path(@provider_organization), method: :delete, class: "ml-2 rounded-lg py-3 px-5 bg-red-500 inline-block font-medium text-white" %>
      <%= link_to "Provider Organizations List", provider_organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-400 inline-block font-medium" %>
    </div>
  </div>
</div>